<?php

use Illuminate\Database\Seeder;

class caracteristicas_cursosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        DB::table('caracteristicas_cursos')->insert(['id'=>"1",'contenido'=>'Identificar el contenido teórico y la fundamentación de los conceptos de la función pública  para relacionarlos como principios rectores de la Administración Pública.','caracteristica_id'=>1,'curso_id'=>1,'created_at'=>NULL,'updated_at'=>NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"2",'contenido'=>'Identificar la utilidad de las herramientas jurídicas  a nivel tanto nacional como territorial  que promueve la función pública en la gestión de lo público. ','caracteristica_id'=>1,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"3",'contenido'=>'Ser capaces de evaluar críticamente la situación institucional territorial en materia de gestión pública y puedan proponer en consecuencia,  medidas de auto corrección en desarrollo de su aptitud para la función pública adquirida ','caracteristica_id'=>1,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"4",'contenido'=>'Desarrollar capacidades para aplicar los contenidos del Módulo  a través del análisis de casos concretos  a la realidad particular que cado uno vive como funcionario/a  ciudadano/a y agente comprometido con una cultura de fortalecimiento democrático y gestión pública integral.','caracteristica_id'=>1,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"5",'contenido'=>'Comprender los nuevos paradigmas de Gestión Pública  con enfoque ético. ','caracteristica_id'=>2,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"6",'contenido'=>'Manejar los conceptos organizacionales en las instituciones públicas territoriales  ','caracteristica_id'=>2,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"7",'contenido'=>'Aplicar los principios y valores que rigen la administración pública  así como la perspectiva de género e inclusión. ','caracteristica_id'=>2,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"8",'contenido'=>'Desarrollar competencias gerenciales en gestión pública','caracteristica_id'=>2,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"9",'contenido'=>'Demostrar actitudes de respeto a los derechos humanos a la igualdad,  la inclusión,  a partir de conductas democráticas que aporten al logro de ambientes de trabajo,  confiables y tolerantes. ','caracteristica_id'=>2,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"10",'contenido'=>'Comprender la función pública como derecho protegido del Estado para disminuir el riesgo antijurídico  ','caracteristica_id'=>2,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"11",'contenido'=>'Manifestar interés para adquirir conocimientos a fin de mantenerse actualizado para el eficiente desempeño de sus funciones con calidad y calidez.','caracteristica_id'=>2,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"12",'contenido'=>'Identificar los preceptos jurídicos básicos que rigen la función pública. ','caracteristica_id'=>3,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"13",'contenido'=>'Identificar las funciones básicas de los entes territoriales y sus competencias para mejorar la gestión pública. ','caracteristica_id'=>3,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"14",'contenido'=>'Evaluar la situación institucional en materia de gestión pública de acuerdo a las aptitudes adquiridas ','caracteristica_id'=>3,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"15",'contenido'=>'Comprender a la realidad particular que cado uno vive en su institución y propender su mejoramiento a partir de las destrezas adquiridas en este diplomado.','caracteristica_id'=>3,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"16",'contenido'=>'Conceptos básicos y normativos de función y gestión pública,  políticas públicas y organización territorial. ','caracteristica_id'=>4,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"17",'contenido'=>'Nuevos modelos y enfoques de la gestión publica','caracteristica_id'=>4,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"18",'contenido'=>'Administración pública con enfoque en el recurso humano.Trabajo en equipo Comunicación Asertiva Evaluación de desempeño con enfoque diferencial. Ética y transparencia en la gestión pública. Calidad del servicio. ','caracteristica_id'=>4,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"19",'contenido'=>'Gerencia estratégica','caracteristica_id'=>4,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"20",'contenido'=>'Buenas prácticas a nivel regional y territorial ','caracteristica_id'=>4,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"21",'contenido'=>'El Módulo está diseñado en función a un formato teórico-práctico y se estructura en función a tres ejes: 1 - Las sesiones presenciales 2- La lectura previa de material a través del aula virtual 3- Los ejercicios prácticos en las sesiones presenciales','caracteristica_id'=>4,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"22",'contenido'=>'Los materiales didácticos  son auxiliares del proceso de enseñanza-aprendizaje. El listado de recurso que han sido desarrollados como facilitadores del aprendizaje son: ','caracteristica_id'=>6,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"23",'contenido'=>'Aula Virtual: Para las sesiones de capacitación virtual  se ha puesto a disposición de los participantes del Módulo una plataforma de aprendizaje en línea (e-learning) a través de Internet.  Los participantes pueden ingresar al sitio de capacitación en línea desde sus casas u oficinas para leer materiales de apoyo y contenidos desarrollados por los instructores  además de realizar ejercicios interactivos,  acceder a otros recursos informativos,  descargar documentos y subir sus tareas. ','caracteristica_id'=>6,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"24",'contenido'=>'Presentaciones en PowerPoint: estas presentaciones muestran informaciones importantes,  complementados con gráficos  para desarrollar los temas específicos del programa. ','caracteristica_id'=>6,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"25",'contenido'=>'Materiales de lectura: son materiales informativos sobre temas de interés para el Módulo.','caracteristica_id'=>6,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"26",'contenido'=>'Videos conferencias: Los participantes pondrán acceder a los videos tutoriales del diplomado para adquirir la experticia y competencia comportamental para el desempeño de sus funciones administrativas.  ','caracteristica_id'=>6,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"27",'contenido'=>' ','caracteristica_id'=>7,'curso_id'=>1,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"28",'contenido'=>'Aprender a ingresar y navegar por la plataforma de SECOP II','caracteristica_id'=>1,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"29",'contenido'=>'Aprender a alistar los requisitos para inscribirse como proveedor del SECOP II','caracteristica_id'=>1,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"30",'contenido'=>'Aprender a vincularse a las entidades públicas a través de la página web.','caracteristica_id'=>1,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"31",'contenido'=>'Aprender a ofrecer los servicios a través de la plataforma SECOP II','caracteristica_id'=>1,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"32",'contenido'=>'Administrar correctamente la página SECOP II ','caracteristica_id'=>2,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"33",'contenido'=>'Cargar adecuadamente los requisitos legales  ','caracteristica_id'=>2,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"34",'contenido'=>'Apoyar a la administración pública en sus competencias','caracteristica_id'=>2,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"35",'contenido'=>'Desarrollar competencias para administración del SECOP II como funcionario ','caracteristica_id'=>2,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"36",'contenido'=>'Cumplir los requerimientos legales ','caracteristica_id'=>2,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"37",'contenido'=>'Identificar el contenido teórico y práctico de la plataforma SECOP II','caracteristica_id'=>3,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"38",'contenido'=>'Identificar la utilidad de las herramientas ofrecidas por la plataforma SECOP II','caracteristica_id'=>3,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"39",'contenido'=>'Ser capaces administrar los recursos ofrecidos por la plataforma  ','caracteristica_id'=>3,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"40",'contenido'=>'Desarrollar capacidades para servirse de la plataforma y formar a otros funcionarios y proveedores  ','caracteristica_id'=>3,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"41",'contenido'=>'Manejo básico de Internet y comprensión del sentido de la WEB  ','caracteristica_id'=>4,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"42",'contenido'=>'Conocimiento pertinente de la plataforma SECOP II,  beneficios y alcances','caracteristica_id'=>4,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"43",'contenido'=>'Marco Normativo nacional e internacional ','caracteristica_id'=>4,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"44",'contenido'=>'Requisitos de alistamiento para la inscripción en la plataforma SECOP II','caracteristica_id'=>4,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"45",'contenido'=>'Acceso e inscripción en la plataforma SECOP II','caracteristica_id'=>4,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"46",'contenido'=>'Navegabilidad dentro de la plataforma SECOP II para proveedores ','caracteristica_id'=>4,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"47",'contenido'=>'Inscripción de entidades pública en el SECOP II','caracteristica_id'=>4,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"48",'contenido'=>'Navegabilidad dentro de la plataforma SECOP II para administradores de entidades públicas','caracteristica_id'=>4,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"49",'contenido'=>'Navegabilidad dentro de la plataforma SECOP II para ordenador del gasto','caracteristica_id'=>4,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"50",'contenido'=>'Navegabilidad dentro de la plataforma SECOP II para funcionarios usuarios','caracteristica_id'=>4,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"51",'contenido'=>'El Módulo está diseñado en función a un formato teórico-práctico y se estructura en función a tres ejes: ','caracteristica_id'=>5,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"52",'contenido'=>'1- Las sesiones a través de videos y conferencias creadas por la plataforma SECOP II,  así como del capacitador orientador del seminario  ','caracteristica_id'=>5,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"53",'contenido'=>'2- La lectura previa de materiales a distancia a través suministrada por la ESCUELA VIRTUAL de ALTA ESPECIALIDAD ','caracteristica_id'=>5,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"54",'contenido'=>'3-  Los ejercicios prácticos que deben ser cargados a la plataforma como evidencia del seminario.  ','caracteristica_id'=>5,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"55",'contenido'=>'Los materiales didácticos  son auxiliares del proceso de enseñanza-aprendizaje. El listado de recurso que han sido desarrollados como facilitadores del aprendizaje son: ','caracteristica_id'=>6,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"56",'contenido'=>'Aula Virtual: Para las sesiones de capacitación a distancia  se ha puesto a disposición de los participantes del Módulo una plataforma de aprendizaje en línea (e-learning) a través de Internet','caracteristica_id'=>6,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"57",'contenido'=>'Los participantes pueden ingresar al sitio de capacitación en línea desde sus casas u oficinas para leer materiales de apoyo y contenidos desarrollados por los instructores,  además de realizar ejercicios interactivos,  acceder a otros recursos informativos  descargar documentos y subir sus tareas. Para acceder al sitio se debe ingresar a: www.altaespecialidad.co','caracteristica_id'=>6,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"58",'contenido'=>'Presentaciones en Powerpoint: estas presentaciones muestran informaciones importantes,  complementados con gráficos  para desarrollar los temas específicos del programa. ','caracteristica_id'=>6,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"59",'contenido'=>'Materiales de lectura: son materiales informativos sobre temas de interés para el Módulo.','caracteristica_id'=>6,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"60",'contenido'=>'Videos tutoriales: son materiales audiovisuales creados por el capacitador y los ofrecidos por la plataforma SECOP II ','caracteristica_id'=>6,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"61",'contenido'=>'Plataforma SECOP II','caracteristica_id'=>7,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"62",'contenido'=>'Ley 1150 de 2007 ','caracteristica_id'=>7,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"63",'contenido'=>'Ley 1712 de 2014','caracteristica_id'=>7,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"64",'contenido'=>'Decreto 4170 de 2011','caracteristica_id'=>7,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"65",'contenido'=>'Decreto 1082 de 2015','caracteristica_id'=>7,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"66",'contenido'=>'Decreto 1083 de 2015','caracteristica_id'=>7,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"67",'contenido'=>'Ley 527 de 1999','caracteristica_id'=>7,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"68",'contenido'=>'Wikipedia ','caracteristica_id'=>7,'curso_id'=>2,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"69",'contenido'=>'Comprender el concepto de cierre fiscal y financiero','caracteristica_id'=>1,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"70",'contenido'=>'Aprender a hacer un cierre fiscal en una entidad pública','caracteristica_id'=>1,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"71",'contenido'=>'Saber cuales son los requisitos que debe cumplir un cierre fiscal ','caracteristica_id'=>1,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"72",'contenido'=>'Interpretar los resultados que arroja el cierre fiscal y financiero.','caracteristica_id'=>1,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"73",'contenido'=>'Prepara al nuevo equipo financiero sobre las condiciones económicas,  fiscales y financieras de la entidad recibida','caracteristica_id'=>1,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"74",'contenido'=>'Saber los contenidos de un cierre fiscal y financiero','caracteristica_id'=>2,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"75",'contenido'=>'Interpretar las cifras y resultados exhibidos   ','caracteristica_id'=>2,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"76",'contenido'=>'Identificar las condiciones financieras y fiscales de su entidad ','caracteristica_id'=>3,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"77",'contenido'=>'Analizar y proyectar la realidad económica de su entidad','caracteristica_id'=>3,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"78",'contenido'=>'Identificar los riesgos financieros y fiscales de su entidad y proponer los ajustes dentro del marco fiscal','caracteristica_id'=>3,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"79",'contenido'=>'Desarrollar capacidades de competencia comportamental en el manejo de los recurso fiscales y financieros de la entidad','caracteristica_id'=>3,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"80",'contenido'=>'Que es el marco fiscal, contenido,  requisitos e interpretación de cifras','caracteristica_id'=>4,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"81",'contenido'=>'Que es cierre fiscal','caracteristica_id'=>4,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"82",'contenido'=>'Que es el cierre financiero  ','caracteristica_id'=>4,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"83",'contenido'=>'Requisitos del cierre fiscal,  alcance y contenido','caracteristica_id'=>4,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"84",'contenido'=>'Requisitos del cierre financiero alcance y contenido','caracteristica_id'=>4,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"85",'contenido'=>'Proyección y tratamiento del déficit o superávit en la siguiente vigencia','caracteristica_id'=>4,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"86",'contenido'=>'Proyección financiera y fiscal en el cuatrienio de gobierno','caracteristica_id'=>4,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"87",'contenido'=>'Que es y como se administran las cuentas por pagar,  las reservas presupuestales y las vigencias futuras','caracteristica_id'=>4,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"88",'contenido'=>'El Módulo está diseñado en función a un formato teórico-práctico y se estructura en función a tres ejes: ','caracteristica_id'=>5,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"89",'contenido'=>'1- Las sesiones a través de videos y conferencias creadas por la plataforma SECOP II,  así como del capacitador orientador del seminario  ','caracteristica_id'=>5,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"90",'contenido'=>'2- La lectura previa de materiales a distancia a través suministrada por la ESCUELA VIRTUAL de ALTA ESPECIALIDAD ','caracteristica_id'=>5,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"91",'contenido'=>'3- Los ejercicios prácticos que deben ser cargados a la plataforma como evidencia del seminario','caracteristica_id'=>5,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"92",'contenido'=>'Los materiales didácticos,  son auxiliares del proceso de enseñanza-aprendizaje. El listado de recurso que han sido desarrollados como facilitadores del aprendizaje son: ','caracteristica_id'=>6,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"93",'contenido'=>'Aula Virtual: Para las sesiones de capacitación a distancia,  se ha puesto a disposición de los participantes del Módulo una plataforma de aprendizaje en línea (e-learning) a través de Internet','caracteristica_id'=>6,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"94",'contenido'=>'Los participantes pueden ingresar al sitio de capacitación en línea desde sus casas u oficinas para leer materiales de apoyo y contenidos desarrollados por los instructores,  además de realizar ejercicios interactivos,   acceder a otros recursos informativos  descargar documentos y subir sus tareas. Para acceder al sitio se debe ingresar a: www.altaespecialidad.co ','caracteristica_id'=>6,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"95",'contenido'=>'Presentaciones en Powerpoint: estas presentaciones muestran informaciones importantes,  complementados con gráficos  para desarrollar los temas específicos del programa. ','caracteristica_id'=>6,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"96",'contenido'=>'Materiales de lectura: son materiales informativos sobre temas de interés para el Módulo.','caracteristica_id'=>6,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"97",'contenido'=>'Videos tutoriales: son materiales audiovisuales creados por el capacitador y los ofrecidos por la plataforma SECOP II ','caracteristica_id'=>6,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"98",'contenido'=>'Decreto Ley 111 de 1996','caracteristica_id'=>7,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"99",'contenido'=>'Ley 819 de 2003','caracteristica_id'=>7,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"100",'contenido'=>'Ley 1483 de 2011 ','caracteristica_id'=>7,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"101",'contenido'=>'Decretos reglamentarios sobre la materia','caracteristica_id'=>7,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"102",'contenido'=>'FUT','caracteristica_id'=>7,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
        DB::table('caracteristicas_cursos')->insert(['id'=>"103",'contenido'=>'Wikipedia ','caracteristica_id'=>7,'curso_id'=>3,'created_at'=> NULL,'updated_at'=> NULL,]);
       
    }
}
